### ISSUE TITLE
Mismatch in video timestamps and trial timestamps 

### ISSUE THREAD

**Issue by shailajaAkella** [AllenInstitute/npc_sessions#114]
Sessions effected:   `660023_2023-08-09` , `666986_2023-08-15`, `644867_2023-02-23`. 

The timestamps from the trial structure were greater than the timestamps from the behavior video for these sessions.

`trials= session.trials[:].stop_times.values[-1]`

**Comment by bjhardcastle** [comment]
I think I found the cause of this:

- sync and mvr were started long before the actual experiment (presumably for a pretest) but not stopped 
- there's a short gap in the camera frame times on sync, where MVR stops briefly and starts recording the files for the experiment:
![image](https://github.com/user-attachments/assets/75a6864d-a603-4542-adf1-dacf8dd343bb)
![image](https://github.com/user-attachments/assets/a0e61679-6b52-4cef-b4c9-a8d76ae62baf)
![image](https://github.com/user-attachments/assets/222a67e6-4919-4dac-b278-3cda48ea2dd4)

I'll try adding something in `npc_mvr` to check for blocks of frametimes like this, and discard all but the one that starts closest to the start time of the experiment video data, or has the closest match in number of frames
