### ISSUE TITLE
Probe spike rate drift

### ISSUE THREAD

**Issue by corbennett** [AllenInstitute/npc_sessions#19]
- [x] Plot probe spike rate over course of experiment to check for slow drift

**Comment by bjhardcastle** [comment]
For the time being we can use the rasters output from SpikeInterface with this snippet:

```python
import npc_lims
import IPython.display

session_id = '660023_2023-08-08'
for path in next(p for p in npc_lims.get_sorted_data_paths_from_s3(session_id) if p.name == 'drift_maps').iterdir():
    display(path.name)
    display(IPython.display.Image(path.read_bytes()))
```

**Comment by corbennett** [comment]
Yeah. These are great and also important to put in the QC. In addition, I've asked Arjun to make some spike rate plots that will make trends in overall firing rate a bit easier to see.

**Comment by bjhardcastle** [comment]
Added these drift maps to Session object and nwb: https://github.com/AllenInstitute/npc_sessions/commit/cb7f094973355b971ff93fcf1c335d44fa421f16

QC notebooks have been moved out of this repo, to `np_notebooks`:
https://github.com/alleninstitute/np_notebooks/commit/af13bd187144fff0a4b2b566ea3419b690ed809e

new task:
- [ ] add all-spike timeseries to `nwb.analysis`
