### ISSUE TITLE
@arjunsridhar12345 rm settings xml, use spike_interface_data.electrode_locations_xy

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#39]
https://github.com/AllenInstitute/npc_sessions/blob/3d7341507a45915dbae82d96b233d49ed050f35d/src/npc_sessions/utils/units.py#L193

**Comment by bjhardcastle** [comment]
@arjunsridhar12345  Did you figure out why SpikeInterface gives x-positions different from settings.xml?

**Comment by arjunsridhar12345** [comment]
@bjhardcastle yeah, it's subtracting by the min x-position (11). Talked to Ethan and he said it should be fine

**Comment by bjhardcastle** [comment]
ok, then the `rel_x` `rel_y` columns in our `nwb.electrodes` table are relative to channel 1 on the probe (1-indexed)
