### ISSUE TITLE
Surface-channels recording upload

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#43]
## Current blockers
- [x] organize the surface-channels recordings raw data with some consistent identifier in their folder name 
- the upload to code ocean (currently on the D3D `sorting` machine) uses [this](https://github.com/AllenInstitute/np_codeocean/blob/main/src/np_codeocean/upload.py) which uses `np_session` to rearrange raw data folders to have a certain structure (ecephys & behavior subfolders)
  - [x] adapt current upload script or make a new one for surface-channels (may require mods to `np_session`)
  - the surface-channels session should not appear in code ocean as the same as the 'main' session: otherwise, when we try to identify the one most-recent sorted data asset, we'll be mixing up the regular units with the surface-channels units (other clashes in metadata etc will inevitably happen at some point too)
    - [x] assign a later start time in the metadata used for the upload "job" csv
    - [x] do anything else required to not mix-up the sessions (may require mods to `np_session`, which works completely under the assumption of 1 session per subject per day)

## Validation
- we need to make sure that `npc_lims` is able to differentiate between the sessions
  - [ ] use the session index: appending `_1` to any session strings used in `tracked_sessions.yaml` should be enough to find correct data assets in code ocean, but this needs checking (with tests) when we have our first upload
- [ ] use `npc_lims/sessions` to open sorted surface-channels data, confirm spike-sorting capsule works & data look reasonable 

## Final jobs
- [ ] #79
- [ ] potentially create a second workflow notebook to run surface channel recording as a separate session, with separate sync file
  - might complicate some file copying

**Comment by bjhardcastle** [comment]
- [ ] update to use new job csv format:
```csv
s3_bucket,platform,subject-id,acq-datetime,modality0,modality0.source,modality1,modality1.source
aind-ephys-data,ecephys,644864,2023-02-02 12:29:19,ecephys,/allen/programs/mindscope/workgroups/np-exp/codeocean/DRpilot_644864_20230202/ephys,behavior-videos,/allen/programs/mindscope/workgroups/np-exp/codeocean/DRpilot_644864_20230202/behavior
```
- [ ] use new upload service (so we run the job on the hpc instead of the sorting computer):
  http://aind-data-transfer-service/

**Comment by bjhardcastle** [comment]
- [ ] add a tag to the uploaded session if possible

**Comment by arjunsridhar12345** [comment]
the upload job failed using the hpc, might be an issue with the symlinks. Talked to Jon, he sent me  the log file which is located below:

"\\allen\aind\scratch\svc_aind_upload\logs\prod\ecephys_660023_2023-08-08_15-11-14_error.out"

Pushed my code to my fork: https://github.com/arjunsridhar12345/np_codeocean

**Comment by bjhardcastle** [comment]
I think the problem is that the symlinks point to `workgroups/dynamicrouting`, which the service account used on the hpc can't read
