### ISSUE TITLE
644864_2023-02-02 missing probes

### ISSUE THREAD

**Issue by egmcbride** [AllenInstitute/npc_sessions#48]
644864_2023-02-02 has only probes A, B, and C. It should also have probes E and F.

This was a session in the np-exp directory. I copied it to dynamicrouting, so it's possible it will work now.

**Comment by bjhardcastle** [comment]
Looks like only `Record Node 103/experiment1/recording1` was uploaded. I'll re-upload

**Comment by bjhardcastle** [comment]
[`d24daced-4973-466a-9b23-275c7bb64c3e`](https://codeocean.allenneuraldynamics.org/data-assets/d24daced-4973-466a-9b23-275c7bb64c3e/ecephys_644864_2023-02-02_12-29-19_sorted_2023-10-12_17-17-29?filters=N4IgZglgNgLgpgJxALhAQylEAaEBHAV0QE8UQ4BjOABwAtiBnAfQDYAWNgDnZxAYHsEMMhQRw08ACa9JcBhRQwERXNTQBzOCgCMqxAAUNW5ACYADLjSSAbmgB2VacmABfXHbQBbY%2BSp1GrBzcbEzmJgDMALRmJtEmTNqxJgCckdrJTAJCcJKhMVHaZmnx2gDsaeUpvDAaDCgA2r409HW47Fw8uLIIENY5IAC6uADWEHZOIGIMBLC8DBAAXsYmJmzhnKVcAKybuJBQciil4YldEmgMcDB1yPWgEBNoLObhm2CRAEY5W5FsLCxRTjaLbvMCJMBsMwUSQmNCcaS4GAQGAHMiUZoBdrBPIROJxBJJVLpXiefgEOzCVDo-zMLHsHFRGL4xKRFJpZIgFxDSY0BD8SQECgQD6o5BKFQgaiITwQBjzfh2G6gawQOAAd0UyjguBV6oAyrQ0GJNUQ3HwavAyJAPFhcPw1XZEABJCZsbThFiSLZbbSRSThChRNgfVaRThgWRxChccRgsxgUq8e2OhAAOS8PjQY0kAAJLggVVQc-woAiQKJxFIAIKU7QsZKld2FNjJAB02j%2BWxMWzYuA%2BFzgAFUEFhULQYDBqAxkAB6GcUflwfhUeytjAHOyOggIDCSYgeGUUBitwTqGeSc6Xa4zt0er0%2Bv0BoMhthhiNwKMxtBxhPn1YXxxfgbIN-jQSJkhDKITFKLYKFKD4PnYQMtFwBdPBlGAXTIeszGSFgzCsDZkg4Ng4DAcJVisChEgoci2C2Z4PngkxJHDCgzF4ZQ7D1UQIGoSly0XGcuN4Cg0CnGY4Cw1BJAQ8JJAoExfRDKhfn7ChwOgjTu2SGJ6LYCJXlE8TpgOAAVYgpTIeY7HUVFUJMyS9SgAh1DIGCzHrBtjIkg5028MgAAoGBqEU4AAShzABRGkc2oPkqDlMZ1Divi4CgMY4BzABpaB%2BCyGATFbLZRP4TxqAIC0IAVaSQFwsxtDQMjUnorYPl%2BCgtiiL4PlSRDwisOBwl6p4OVwbM4AADz1C0fDQ6gDikUSCBCsqAFkrisc4UFAC8ahzA4%2BlHEBul6HIcz2tBeCmqUem8CkcxgSyfGpFoSX5DBkVIVAosmpQ0CoTAZiNHN0soJR%2BBpaqoH4dRSFwaYPgAK3BnMHmwoIeDNKALkw8Ypv6ZA6wbJsKNKVsW29MwW0sCgkT6AB5B1EBuO4QHR1Bb09b1fX9QM1NDcNIxiaNOFjQoE14A9M2zPNEELLKSzLOBPCzY6tx3Ut9y8CAjwAAXXOA7DGELkUquATwQNyuXGuwKpgAARbbbnuR5njMV42HeL4vV%2Bf5AWBUFwUhaFYXhapkVFJoaUCDoQjCRlYhiAlWSJMaQFJckBNezFMfj-I8WTlk2WJG3yzECQchrAAZNAvmOhm6ZzU4cwT5uzCJxNcBxkKnXxyaclr%2BuyEbmBm5MbBW-ydvTBMOZFjgIf0rIcxW04ZIcwAcQAIVK9DkWw3S8II3hZSdmorxQMAMEuFwgA)

F skipped by `SpikeInterface`:
```
...

Preprocessing recording: experiment1_Record Node 104#Neuropix-PXI-100.ProbeD-AP_recording1
	Duration: 4645.29 s
	Bad channel detection:
		- dead channels - 145
		- noise channels - 118
		- out channels - 0
	More than 50.0% bad channels (263). Skipping further processing for this recording.

Preprocessing recording: experiment1_Record Node 104#Neuropix-PXI-100.ProbeE-AP_recording1
	Duration: 4645.3 s
	Bad channel detection:
		- dead channels - 1
		- noise channels - 0
		- out channels - 5
	Removing 5 out channels
	Removing 1 channels after cmr preprocessing
write_binary_recording with n_jobs = 16 and chunk_size = 30000

Preprocessing recording: experiment1_Record Node 104#Neuropix-PXI-100.ProbeF-AP_recording1
	Duration: 4645.28 s
	Bad channel detection:
		- dead channels - 183
		- noise channels - 152
		- out channels - 0
	More than 50.0% bad channels (335). Skipping further processing for this recording.
```

**Comment by bjhardcastle** [comment]
This is fixed now - units available for `ABCE`
