### ISSUE TITLE
Sessions missing units

### ISSUE THREAD

**Issue by egmcbride** [AllenInstitute/npc_sessions#49]
Sessions 644866_2023-02-07 and 644866_2023-02-08 appear to be missing, but there is no obvious reason why. 

FYI 644866_2023-02-07 was in np-exp, so I copied it to dynamicrouting, which might help.

**Comment by bjhardcastle** [comment]
`644866_2023-02-07` is failing in sound alignment: 
- initial trials are fine, but at some point the requested range of nidaq samples returns an empty array
- the exception raised by `np.correlate` wasn't very helpful (`ValueError("'a' cannot be empty")` so I've added a check + exception with more info
- still need to figure out whether there's nidaq data missing, or our trial times are bad

**Comment by bjhardcastle** [comment]
`644866_2023-02-07` was missing a probe in the sorted data, and had partially incomplete Record Node folders in the raw data upload
- uploading and re-sorting again

**Comment by bjhardcastle** [comment]
Looks fine now.
