### ISSUE TITLE
Sound alignment failing

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#52]
Currently affecting: 
- `670181_2023-07-20`
- `644866_2023-02-07`
- `670248_2023-08-03`

initial trials are fine, but at some point the requested range of nidaq samples returns an empty array

**Comment by egmcbride** [comment]
670181_2023-07-20 was a split recording -- recording during the task should be intact, but RFmapping is separate.
670248_2023-08-03 was also a split recording -- the last ~5 min of task was lost
Are these recoverable?

Not sure what's going on with 644866_2023-02-07

**Comment by bjhardcastle** [comment]
Modified processing so that when nidaq data is missing we fallback to `latency=np.nan`
- also updated `start_time_on_sync` to use `np.nansum([trigger_time_on_sync, latency])` 

explanation:
  - the range of nidaq data is 1:1 with ephys data, so these trials with missing sound recordings are also missing ephys data
  - accurate timing info is only required for ephys analysis, or investigating stim timing throughout a session (which will encounter nan values for these trials)
