### ISSUE TITLE
`662983_2023-05-16` errored: `FileNotFoundError("Expected a single NI-DAQmx folder to exist ...`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#53]
`..., but found: [S3Path('s3://aind-ephys-data/ecephys_662983_2023-05-16_12-33-22/ecephys_clipped/Record Node 103/experiment1/recording1/continuous/NI-DAQmx-102.PXI-6133'), S3Path('s3://aind-ephys-data/ecephys_662983_2023-05-16_12-33-22/ecephys_clipped/Record Node 104/experiment1/recording1/continuous/NI-DAQmx-102.PXI-6133')]")`

**Comment by egmcbride** [comment]
Looks like we accidentally recorded the NIDAQ to both record nodes. Should be OK to delete or ignore one.

**Comment by bjhardcastle** [comment]
Deleted from continuous data from Record Node 104 folder, and removed corresponding entry from `structure.oebin` on the Isilon and on S3
- `\\allen\programs\mindscope\workgroups\templeton\TTOC\pilot recordings\2023-05-16_10-25-25_662983`
- `s3://aind-ephys-data/ecephys_662983_2023-05-16_12-33-22/ecephys_clipped`
- `s3://aind-ephys-data/ecephys_662983_2023-05-16_12-33-22/ecephys_compressed`
