### ISSUE TITLE
`644866_2023-02-08` uncertain probes inserted

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#63]
- surface images show all probes inserted
- OpenEphys data is present for all probes
- no insertion `.json` exists
-  in `npc_sessions`, inserted probes are discovered with `E` missing:
```python
>>> import npc_sessions
>>> s = npc_sessions.DynamicRoutingSession(
        '644866_2023-02-08',
    )
>>> print(s.probe_letters_inserted)
('A', 'B', 'C', 'D', 'F')
```

which comes from:
```
S3Path('s3://aind-scratch-data/arjun.sridhar/tissuecyte_cloud_processed/644866/Probe_A2_channels_644866_warped_processed.csv')
S3Path('s3://aind-scratch-data/arjun.sridhar/tissuecyte_cloud_processed/644866/Probe_B2_channels_644866_warped_processed.csv')
S3Path('s3://aind-scratch-data/arjun.sridhar/tissuecyte_cloud_processed/644866/Probe_C2_channels_644866_warped_processed.csv')
S3Path('s3://aind-scratch-data/arjun.sridhar/tissuecyte_cloud_processed/644866/Probe_D2_channels_644866_warped_processed.csv')
S3Path('s3://aind-scratch-data/arjun.sridhar/tissuecyte_cloud_processed/644866/Probe_F2_channels_644866_warped_processed.csv')
```

however this doesn't match the output from spikeinterface in `191eda73-766d-41b7-9000-78c54b8b2f75` [here](https://codeocean.allenneuraldynamics.org/data-assets/191eda73-766d-41b7-9000-78c54b8b2f75/ecephys_644866_2023-02-08_16-01-11_sorted_2023-10-13_00-07-13?filters=N4IgZglgNgLgpgJxALhAQylEAaEBnAewRhRAGME414ATHEGuPMlGBAVzlwAc0BzOCgCMPRAAV%2Bg5ACYADLjQ0AbmgB2ZOHWTAAvrlVoAtlJBwN3ABYBPPAH0AbABZHADnv3bc6QGYAtLOl-F1she38hXyEhW0JiTU8AvyFZSO9bWRTZAHZU%2Bhh%2BPBQAbVNza0KeBAINPDxNeidXdxAAXVwAawhVLRBKPHZYejwIAC8paQBWAE4sqMcnKelcSCgmFCmhGdwaajQ6mELkItAIHrkaRgmM3xoNMF9HNCyyXzQXFwAjXzhvRw-ZsBXaQzPIQGCrUhmOCWGwOZxuDxePwBIIhMKyCJReiGAjsVQkVBQmF2RoIhI%2BfyBWTBULhSJCEA6Nq9aFVGjsMgQD4Q5BsTiiBCGCC1CAEVSHUBKCBwADurA4XBAUtlAGULGhKPLOHp8Pl4KRIAYsLgCDLVIgAJI9RxCbz2GgTCYRGjeMh%2BP7SRy%2BFxgRiUsiuKhgZJgLL0U3mhAAOSMJjQXRoAAI6ggpRpEwQoHRcBQqLQAIIE0IzISO%2BzebwAOhtLgm9lLuA%2BezgAFUEFhUBYYDBuHhkAB6ftkAiMapUVSVjCrVTm9gIDA0KwGIVkPCVoh8fs7fL7PD9m12h1Om6u90fT3e31wf2BtDB2Sh-ubISaJ5%2BLLuGgPIT-XxTDIpFkLhkBMfyfNIoYTPQw6GEKMBWqQ9j-lM9iyIoLhZFMziOHAYDeJ6ihkEI0hkHhjh1tI-znjQPpkLI9AcKoKoUBA3AEuQI5wP2jHQWgvYDHACGoDQHwfN4tzSBE54aA8TYvIszy%2BJM-6eqBPjeGGOZ8f0qwACpWNwJjDKofAQlp-GrCqUDsHwpBZFcSEguZOlwDGxikAAFHg%2BTcnAACUiYAKLEom3BVDUxl8KFrFwFAXRwImADS0AELEMDSJWUE5gQhjcOweqiqoQnoFMFagXRvj-LILw4a6rwTBeOxgHed5ZDhHwsLgCZwAAHiqeomDB3CrLQ0HsN5OUALJwPk25oCgoBzYmqxKLFpCMAgECrUmc30L1hmbcY%2BKJjABkmES5TYiOGBglYpCBT1bBoBomADBqiaxWYbAEMSopQAQfB3bg-QfAAVl9ianIh8LNDqUB7PB3S9fUyDFrMjolpWyQYhWSzoGQMBbXAADyZqIIcxwgFDqAHvajrOqeskXj6foBAGLhBiGmkgMucYJsmiBpglmbZqYhjxh2PNwHOC5LkYECrgAAlOcCqF03lgvlcDrggtlMl1qh5TAAAiuzFCcZyyBccBXCkty4Q8TwvG8nzfL8-xCICAROSAhPgudZSwqS7jksiVI0uimIMrgOJ4uxF1BzDiKJJSqK0hi9KMsyubUJohYADJoB8a2oMTBOJsR2CJkiFdZMg2T0PD3kWkjPWaIXxeS2XMAV0s1eJLXqPSEMoxwB3JcgJ6WMuImADiABC0E5XBiHIah81dXgps7jNKDNVAdQ6EAA):
- `B` is skipped due to >50% bad channels
- drift maps all show data on remaining `ACDEF`

Is it possible that the probe letters on the annotations are mixed up?

**Comment by egmcbride** [comment]
I checked the scope images and histology. It does look like E was inserted, but I can't find any evidence of dye track in the histology. It's possible the dye was faint, or the probe didn't get dipped enough in the dye. 

Since we don't know where it was, this probe is probably a lost cause, and we should either not include it or include it, but not label it with areas.

**Comment by egmcbride** [comment]
B was also inserted -- I think we need to better understand how it's deciding what is a "bad" or "noisy" channel
